add lastPlayed column
AB1908/GOG-Galaxy-Export-Script pull request #36
Opened 2020-12-22 12:01 UTC by DanielReid

Hey, thought this extra option might be helpful.

2020-12-23 09:47 UTC, Varstahl reviewed
Just found a bug in the export, gotta look through it more in depth.

2020-12-23 09:47 UTC, Varstahl commented on galaxy_library_export.py
> +			[['--LastPlayed'], ba('lastPlayed', 'last time the game was played')],
Rename the parameter in `--last-played`, all lower case and with a dash, to keep consistency.

2020-12-23 09:55 UTC, AB1908 commented
Good catch. I missed that.

2020-12-23 10:06 UTC, Varstahl requested changes
The last changes to fix incorrect behaviour and inconsistencies.

2020-12-23 10:06 UTC, Varstahl commented on galaxy_library_export.py
> +				dbCondition='LASTPLAYEDDATES.gameReleaseKey=MasterList.releaseKey',
This needs to be a left join, otherwise all games without a playtime won't be exported. Remove ref and condition, and add this:

```py
				dbCustomJoin='LEFT JOIN LASTPLAYEDDATES ON LASTPLAYEDDATES.gameReleaseKey=MasterList.releaseKey',
```

2020-12-23 10:06 UTC, Varstahl commented on galaxy_library_export.py
> +						includeField(result, 'lastPlayed', positions['lastPlayed'], paramName='lastPlayed')
`, paramName='lastPlayed'` should be omitted, since it matches the column name.

2020-12-23 10:54 UTC, DanielReid commented
Pushed fixes, sorry for the mistakes. The SQL and optional argument system was a bit over my head :)

2020-12-23 11:30 UTC, Varstahl approved these changes
Everything looks in order

2020-12-23 11:32 UTC, Varstahl commented
> Pushed fixes, sorry for the mistakes. The SQL and optional argument system was a bit over my head :)

Np, it's a pretty good job. The SQL is a bit nightmare-ish. Before modularizing the queries it was about 5 rows long, and even with the helper functions it's still pretty heavy to digest.

2021-07-28 20:10 UTC, TheMelmacian commented
I merged this locally to the actual head and everything works as expected.

2022-04-13 21:45 UTC, AB1908 commented
Big oof, been long while since I've looked at my repos. Does anyone want to resolve the branch conflict?

2022-04-21 21:45 UTC, TheMelmacian commented
The feature was merged with https://github.com/AB1908/GOG-Galaxy-Export-Script/pull/58 and the PR can be closed.

2022-04-21 22:22 UTC, AB1908 commented
Gotcha, thanks for the heads up.

2022-04-21 22:22 UTC, closed without merging